spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://i8b206.p.ssafy.io:3306/coogether?serverTimezone=Asia/Seoul
    username: root
    password: 1234
#    url: jdbc:mysql://localhost:3306/coogether?serverTimezone=Asia/Seoul
#    username: ssafy
#    password: ssafy
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true
        use_sql_comments: true

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

logging.level:
  org.hibernate.SQL: debug
  com.amazonaws.util.EC2MetadataUtils: error
# org.hibernate.type: trace


